import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs'
import logo from '../public/logo.png'
import AdelphiAppPhoto from '../public/adelphi-app.jpg'
import Header from '../components/header'

export default function AdelphiApp() {
    const [darkMode, setDarkMode] = useState(false);
    return (
        <div className={ darkMode ? 'dark' : '' }>
            <Head>
                <title>Adelphi University App - Scott Finkelstein</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header darkMode={ darkMode } setDarkMode={ setDarkMode } />
            <main className='dark:bg-black'>
                <div className='px-3 flex'>
                    <Image src={ AdelphiAppPhoto } alt="" />
                    <div>
                        <h2 className='text-3xl dark:text-white'>Adelphi University App</h2>
                        <p className='font-monserrat dark:text-white italic'>Project Lead, Principal iOS Developer</p>
                        <p className='font-monserrat dark:text-white'>The Adelphi App focuses on the resources that students use most and features a clean and easy-to-navigate design.</p>
                    </div>
                </div>
            </main>
        </div>
    );
}