import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs'
import logo from '../public/logo.png'
import AdelphiAppPhoto from '../public/adelphi-app-insta.png'

export default function AdelphiApp() {
    const [darkMode, setDarkMode] = useState(false);

    return (
        <div className={ darkMode ? 'dark' : '' }>
            <Head>
                <title>Adelphi University App - Scott Finkelstein</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className='flex justify-between py-10 px-3 dark:bg-black'>
                <div className="flex items-top gap-1">
                    <a href="/"><Image src= { logo } alt="" width={ 40 } height={ 40 } /></a>
                    <div>
                    <h1 className="font-antonio font-medium text-2xl text-sky-800 dark:text-sky-100"><a href="/">Scott Finkelstein</a></h1>
                    </div>
                </div>
            
                <ul>
                <li>
                    { !darkMode ?
                    <BsFillMoonStarsFill onClick={ () => setDarkMode(!darkMode) } className='text-xl mr-3' />
                    : <BsFillSunFill onClick={ () => setDarkMode(!darkMode) } className='text-xl mr-3 text-white' />
                    }
                    
                </li>
                </ul>
            </header>
            <main className='dark:bg-black'>
                <div className='primary-bar relative px-3'>
                    <Image src={ AdelphiAppPhoto } />
                    <h2 className='text-3xl dark:text-white'>Adelphi University App</h2>
                    <p className='font-monserrat dark:text-white italic'>Project Lead, Principal iOS Developer</p>
                    <p className='font-monserrat dark:text-white'>The Adelphi App focuses on the resources that students use most and features a clean and easy-to-navigate design.</p>
                    
                </div>
            </main>
        </div>
    );
}